"""add parse cost tracking to documents

Revision ID: 1859523e53de
Revises: e1f2a3b4c5d6
Create Date: 2026-07-16 15:32:49.533641

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1859523e53de'
down_revision: Union[str, None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('parse_cost_usd', sa.Numeric(precision=10, scale=6), server_default='0', nullable=False))
    op.add_column('documents', sa.Column('parse_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'parse_count')
    op.drop_column('documents', 'parse_cost_usd')
    # ### end Alembic commands ###
