"""add_verified_fields_to_invoices

Revision ID: 11154f78c326
Revises: 4424d8ac3601
Create Date: 2026-05-14 15:47:38.009708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11154f78c326'
down_revision: Union[str, None] = '4424d8ac3601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('invoices', sa.Column('verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'verified_at')
    op.drop_column('invoices', 'verified')
    # ### end Alembic commands ###
